//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocApi.DataLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MySQLquery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MySQLquery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocApi.DataLayer.MySQLquery", typeof(MySQLquery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DOM_ID,NAME,DESCRIPTION FROM DOMAIN.
        /// </summary>
        internal static string GetAllDomain {
            get {
                return ResourceManager.GetString("GetAllDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SUB_DOM_ID, DOM_ID, NAME, DESCRIPTION FROM SUB_DOMAIN.
        /// </summary>
        internal static string GetAllSubDomain {
            get {
                return ResourceManager.GetString("GetAllSubDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DOM_ID,NAME,DESCRIPTION FROM DOMAIN WHERE DOM_ID = {0}.
        /// </summary>
        internal static string GetDomain {
            get {
                return ResourceManager.GetString("GetDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT QC_ID , DOM_ID, SUB_DOM_ID, NAME, DESCRIPTION FROM QUESTION_CATEGORY.
        /// </summary>
        internal static string GetQuestionCat {
            get {
                return ResourceManager.GetString("GetQuestionCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT QI_ID, SQC_ID, QC_ID, DOM_ID, SUB_DOM_ID, NAME, DESCRIPTION FROM QUESTION_ITEM.
        /// </summary>
        internal static string GetQuestionItem {
            get {
                return ResourceManager.GetString("GetQuestionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SUB_DOM_ID, DOM_ID, NAME, DESCRIPTION FROM SUB_DOMAIN
        ///WHERE DOM_ID={0}.
        /// </summary>
        internal static string GetSubDomainById {
            get {
                return ResourceManager.GetString("GetSubDomainById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SQC_ID, QC_ID, DOM_ID, SUB_DOM_ID, NAME, DESCRIPTION FROM SUB_QUESTION_CATEGORY.
        /// </summary>
        internal static string GetSubQuestionCat {
            get {
                return ResourceManager.GetString("GetSubQuestionCat", resourceCulture);
            }
        }
    }
}
