//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocApi.DataLayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MySQLquery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MySQLquery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocApi.DataLayer.MySQLquery", typeof(MySQLquery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CONTROL_MASTER SET DEL_FLG=&apos;Y&apos; WHERE  CM_ID= {0}.
        /// </summary>
        internal static string DeleteControlMaster {
            get {
                return ResourceManager.GetString("DeleteControlMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE DOCUMENT_MASTER SET DEL_FLG=&apos;Y&apos; WHERE DM_ID={0}.
        /// </summary>
        internal static string DeleteDocumentMaster {
            get {
                return ResourceManager.GetString("DeleteDocumentMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE DOMAIN SET DEL_FLG=&apos;Y&apos; WHERE DOM_ID={0}.
        /// </summary>
        internal static string DeleteDomain {
            get {
                return ResourceManager.GetString("DeleteDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE QUESTION_CATEGORY SET DEL_FLG=&apos;Y&apos; WHERE  QC_ID={0}.
        /// </summary>
        internal static string DeleteQuestionCategory {
            get {
                return ResourceManager.GetString("DeleteQuestionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE QUESTION_CONTROL SET DEL_FLG=&apos;Y&apos; WHERE  QCT_ID= {0}.
        /// </summary>
        internal static string DeleteQuestionControl {
            get {
                return ResourceManager.GetString("DeleteQuestionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE QUESTION_ITEM SET DEL_FLG=&apos;Y&apos; WHERE  QI_ID= {0}.
        /// </summary>
        internal static string DeleteQuestionItem {
            get {
                return ResourceManager.GetString("DeleteQuestionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SUB_DOMAIN SET DEL_FLG=&apos;Y&apos; WHERE  SUB_DOM_ID={0}.
        /// </summary>
        internal static string DeleteSubDomain {
            get {
                return ResourceManager.GetString("DeleteSubDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SUB_QUESTION_CATEGORY SET DEL_FLG=&apos;Y&apos; WHERE  SQC_ID= {0}.
        /// </summary>
        internal static string DeleteSubQuestionCategory {
            get {
                return ResourceManager.GetString("DeleteSubQuestionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DOM_ID,NAME,DESCRIPTION,ORGL_STAMP, ORGL_USER, UPDT_STAMP, UPDT_USER, DEL_FLG FROM DOMAIN   WHERE DEL_FLG=&apos;N&apos;.
        /// </summary>
        internal static string GetAllDomain {
            get {
                return ResourceManager.GetString("GetAllDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SUB_DOM_ID, DOM_ID, NAME, DESCRIPTION, ORGL_STAMP, ORGL_USER, UPDT_STAMP, UPDT_USER, DEL_FLG FROM SUB_DOMAIN  WHERE DEL_FLG=&apos;N&apos;.
        /// </summary>
        internal static string GetAllSubDomain {
            get {
                return ResourceManager.GetString("GetAllSubDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  CM_ID , CONTROL_TYP, NAME, LABEL, SAMPLE_PIC, DEL_FLG, ORGL_USER, ORGL_STAMP, UPDT_USER, UPDT_STAMP FROM CONTROL_MASTER WHERE DEL_FLG=&apos;N&apos;.
        /// </summary>
        internal static string GetControlMaster {
            get {
                return ResourceManager.GetString("GetControlMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DM_ID , SUB_DOM_ID , CONTENT FROM DOCUMENT_MASTER WHERE SUB_DOM_ID = {0} AND DEL_FLG=&apos;N&apos;.
        /// </summary>
        internal static string GetDocumentMaster {
            get {
                return ResourceManager.GetString("GetDocumentMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT DOM_ID,NAME,DESCRIPTION, ORGL_STAMP, ORGL_USER, UPDT_STAMP, UPDT_USER, DEL_FLG FROM DOMAIN WHERE DOM_ID = {0}  AND DEL_FLG=&apos;N&apos;.
        /// </summary>
        internal static string GetDomain {
            get {
                return ResourceManager.GetString("GetDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT QC_ID , DOM_ID, SUB_DOM_ID, NAME, DESCRIPTION,ORGL_USER, SEQ_NO ,ORGL_STAMP, UPDT_USER, UPDT_STAMP, DEL_FLG FROM QUESTION_CATEGORY WHERE  SUB_DOM_ID={0} AND DEL_FLG=&apos;N&apos;.
        /// </summary>
        internal static string GetQuestionCat {
            get {
                return ResourceManager.GetString("GetQuestionCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT QC_ID , DOM_ID, SUB_DOM_ID, NAME, DESCRIPTION,ORGL_USER, SEQ_NO ,ORGL_STAMP, UPDT_USER, UPDT_STAMP, DEL_FLG FROM QUESTION_CATEGORY WHERE SUB_DOM_ID={0}.
        /// </summary>
        internal static string GetQuestionCatBySubDomId {
            get {
                return ResourceManager.GetString("GetQuestionCatBySubDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT QCT_ID, QI_ID ,SQC_ID,QC_ID, DOM_ID ,SUB_DOM_ID ,NAME ,LABEL, HINT ,OTHDESC ,LISTOFVAL ,CONTROL_ID ,SEQ_NO ,DEL_FLG ,ORGL_USER ,ORGL_STAMP, UPDT_USER ,UPDT_STAMP FROM QUESTION_CONTROL WHERE QI_ID={0}  AND DEL_FLG=&apos;N&apos;.
        /// </summary>
        internal static string GetQuestionControl {
            get {
                return ResourceManager.GetString("GetQuestionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Q.QCT_ID, Q.QI_ID , Q.SQC_ID, Q.QC_ID, Q.DOM_ID , Q.SUB_DOM_ID , Q.NAME , Q.LABEL, Q.HINT , Q.OTHDESC , Q.LISTOFVAL , Q.CONTROL_ID , Q.SEQ_NO , Q.DEL_FLG ,
        ///       C.CONTROL_TYP , C.NAME CONTROL_NAME , C.LABEL CONTROL_LABEL, C.SAMPLE_PIC
        ///FROM QUESTION_CONTROL Q , CONTROL_MASTER C 
        ///WHERE Q.QI_ID={0}  
        ///AND Q.DEL_FLG=&apos;N&apos;
        ///AND Q.CONTROL_ID = C.CM_ID
        ///AND C.DEL_FLG=&apos;N&apos;.
        /// </summary>
        internal static string GetQuestionControlAndMaster {
            get {
                return ResourceManager.GetString("GetQuestionControlAndMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT QI_ID, SQC_ID, QC_ID, DOM_ID, SUB_DOM_ID, NAME, DESCRIPTION, SEQ_NO ,ORGL_USER, ORGL_STAMP, UPDT_USER, UPDT_STAMP , DEL_FLG FROM QUESTION_ITEM WHERE  SQC_ID={0}  AND DEL_FLG=&apos;N&apos;.
        /// </summary>
        internal static string GetQuestionItem {
            get {
                return ResourceManager.GetString("GetQuestionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT QI_ID, SQC_ID, QC_ID, DOM_ID, SUB_DOM_ID , NAME, DESCRIPTION, SEQ_NO ,ORGL_USER, ORGL_STAMP, UPDT_USER, UPDT_STAMP , DEL_FLG FROM QUESTION_ITEM WHERE  SUB_DOM_ID={0}  AND DEL_FLG=&apos;N&apos; .
        /// </summary>
        internal static string GetQuestionItemBySubDomain {
            get {
                return ResourceManager.GetString("GetQuestionItemBySubDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SUB_DOM_ID, DOM_ID, NAME, DESCRIPTION, ORGL_USER, ORGL_STAMP, UPDT_USER, UPDT_STAMP , DEL_FLG FROM SUB_DOMAIN
        ///WHERE DOM_ID={0} AND DEL_FLG=&apos;N&apos;.
        /// </summary>
        internal static string GetSubDomainByDomId {
            get {
                return ResourceManager.GetString("GetSubDomainByDomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT SQC_ID, QC_ID, DOM_ID, SUB_DOM_ID, NAME, DESCRIPTION , SEQ_NO , ORGL_USER, ORGL_STAMP, UPDT_USER, UPDT_STAMP, DEL_FLG FROM SUB_QUESTION_CATEGORY WHERE QC_ID={0} AND DEL_FLG=&apos;N&apos;.
        /// </summary>
        internal static string GetSubQuestionCat {
            get {
                return ResourceManager.GetString("GetSubQuestionCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO CONTROL_MASTER ( CONTROL_TYP,NAME,  LABEL , SAMPLE_PIC , DEL_FLG  ,  ORGL_USER, ORGL_STAMP  ) VALUES(  {0} , {1} , {2},  {3} , {4} , {5}, {6}).
        /// </summary>
        internal static string InsertControlMaster {
            get {
                return ResourceManager.GetString("InsertControlMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO DOCUMENT_MASTER( SUB_DOM_ID , CONTENT, DEL_FLG, ORGL_USER, ORGL_STAMP) values( {0} , {1} , {2} , {3} , {4} ).
        /// </summary>
        internal static string InsertDocumentMaster {
            get {
                return ResourceManager.GetString("InsertDocumentMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO DOMAIN(NAME, DESCRIPTION, DEL_FLG, ORGL_USER, ORGL_STAMP) values( {0} , {1} , {2},  {3} , {4}).
        /// </summary>
        internal static string InsertDomain {
            get {
                return ResourceManager.GetString("InsertDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO QUESTION_CATEGORY (DOM_ID , SUB_DOM_ID ,NAME , DESCRIPTION , SEQ_NO, DEL_FLG , ORGL_USER , ORGL_STAMP ) VALUES( {0} , {1} , {2},  {3} , {4} , {5}, {6}, {7}).
        /// </summary>
        internal static string InsertQuestionCategory {
            get {
                return ResourceManager.GetString("InsertQuestionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO QUESTION_CONTROL ( QI_ID , SQC_ID , QC_ID , DOM_ID , SUB_DOM_ID , NAME , LABEL , HINT , OTHDESC , LISTOFVAL , CONTROL_ID , SEQ_NO , DEL_FLG , ORGL_USER, ORGL_STAMP) VALUES(  {0} , {1} , {2},  {3} , {4} , {5}, {6}, {7}, {8} , {9} ,{10} , {11} ,{12}, {13}, {14}).
        /// </summary>
        internal static string InsertQuestionControl {
            get {
                return ResourceManager.GetString("InsertQuestionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO QUESTION_ITEM ( SQC_ID , QC_ID	,  DOM_ID , SUB_DOM_ID , NAME , DESCRIPTION , SEQ_NO , DEL_FLG , ORGL_USER , ORGL_STAMP ) VALUES( {0} , {1} , {2},  {3} , {4} , {5}, {6}, {7}, {8} , {9} ).
        /// </summary>
        internal static string InsertQuestionItem {
            get {
                return ResourceManager.GetString("InsertQuestionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO SUB_DOMAIN (DOM_ID, NAME , DESCRIPTION, DEL_FLG, ORGL_USER, ORGL_STAMP ) VALUES( {0} , {1} , {2},  {3} , {4} , {5}).
        /// </summary>
        internal static string InsertSubDomain {
            get {
                return ResourceManager.GetString("InsertSubDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO SUB_QUESTION_CATEGORY ( QC_ID , DOM_ID , SUB_DOM_ID , NAME , DESCRIPTION , SEQ_NO , DEL_FLG , ORGL_USER , ORGL_STAMP ) VALUES( {0} , {1} , {2},  {3} , {4} , {5}, {6}, {7}, {8} ).
        /// </summary>
        internal static string InsertSubQuestionCategory {
            get {
                return ResourceManager.GetString("InsertSubQuestionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE CONTROL_MASTER SET CONTROL_TYP={0} ,  NAME={1} , LABEL={2} , SAMPLE_PIC={3} , UPDT_USER={4} , UPDT_STAMP={5} WHERE  CM_ID={6}.
        /// </summary>
        internal static string UpdateControlMaster {
            get {
                return ResourceManager.GetString("UpdateControlMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE DOCUMENT_MASTER SET SUB_DOM_ID={0} , CONTENT={1} , UPDT_USER={2} , UPDT_STAMP={3}  WHERE  DM_ID={4}.
        /// </summary>
        internal static string UpdateDocumentMaster {
            get {
                return ResourceManager.GetString("UpdateDocumentMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE DOMAIN SET NAME={0}   , DESCRIPTION={1}, UPDT_USER={2}  , UPDT_STAMP={3} WHERE  DOM_ID={4}.
        /// </summary>
        internal static string UpdateDomain {
            get {
                return ResourceManager.GetString("UpdateDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE QUESTION_CATEGORY SET DOM_ID={0} , SUB_DOM_ID={1} , NAME={2} , DESCRIPTION={3} , SEQ_NO={4} , UPDT_USER={5} , UPDT_STAMP={6} WHERE  QC_ID={7}.
        /// </summary>
        internal static string UpdateQuestionCategory {
            get {
                return ResourceManager.GetString("UpdateQuestionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE QUESTION_CONTROL SET QI_ID={0} , SQC_ID={1} , QC_ID={2} , DOM_ID={3} , SUB_DOM_ID={4} , NAME={5} , LABEL={6} , HINT={7} , OTHDESC={8} , LISTOFVAL={9} , CONTROL_ID={10} , SEQ_NO={11} , UPDT_USER={12} , UPDT_STAMP={13} WHERE  QCT_ID={14}.
        /// </summary>
        internal static string UpdateQuestionControl {
            get {
                return ResourceManager.GetString("UpdateQuestionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE QUESTION_ITEM SET SQC_ID={0} , QC_ID={1} , DOM_ID={2} , SUB_DOM_ID={3} , NAME={4} , DESCRIPTION={5} , SEQ_NO={6} , UPDT_USER={7} , UPDT_STAMP={8} WHERE  QI_ID={9}.
        /// </summary>
        internal static string UpdateQuestionItem {
            get {
                return ResourceManager.GetString("UpdateQuestionItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SUB_DOMAIN SET DOM_ID={0} , NAME={1} , DESCRIPTION={2} , UPDT_USER={3} , UPDT_STAMP={4} WHERE  SUB_DOM_ID={5}.
        /// </summary>
        internal static string UpdateSubDomain {
            get {
                return ResourceManager.GetString("UpdateSubDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SUB_QUESTION_CATEGORY SET QC_ID={0} , DOM_ID={1} , SUB_DOM_ID={2} , NAME={3} , DESCRIPTION={4} , SEQ_NO={5} , UPDT_USER={6} , UPDT_STAMP={7} WHERE  SQC_ID={8}.
        /// </summary>
        internal static string UpdateSubQuestionCategory {
            get {
                return ResourceManager.GetString("UpdateSubQuestionCategory", resourceCulture);
            }
        }
    }
}
